- index.js
It's handy to be able to access to bel's element creation function so that you can compose it with other hyperx processing. For example, a few hacks from this weekend:
* https://github.com/chromakode/diablo/blob/83ec0357df45a4e465d6832f4e77d7f25c033ab0/index.js#L12
* https://github.com/chromakode/yo-yo/blob/1dcdde259d2b34d20f8b2978f347a99098f63e8a/index.js#L7
I think it'd make sense to call this `bel.createElement` while retaining the current hyperx default export. What do you think?
> Expose belCreateElement function in module

- index.js
- test/elements.js
This improves symmetry with inner/outerHTML, which makes diffing via `morphdom` more efficient.
Consider this example:
```js
var who = 'world'
var exclamation = ['!', ':)']
bel`<div>hello ${who}${exclamation}`
```
`hyperx` passes bel: `tag: 'div', props: Object{}, children: ['hello ', 'world', ['!', ' :)']]`
Currently, `bel` creates a separate text node for each string (illustrated w/ newlines):
```
<div>
hello
world
!
:)
</div>
```
If we take that output and then stringify the tree via `outerHTML`, the text nodes are effectively merged together.
Thus, if we use `morphdom` to diff a tree generated by `bel` with the same output fetched from an html file, nodes currently get unnecessarily removed and recreated because the trees don't match up.
It turns out to be pretty easy to just merge …
> Combine adjacent text nodes

- README.md
- index.js
- package.json
- test/index.js
- test/onload.js
@yoshuawuyts Take a look please? :)
I'm just calling the function instead of actually creating a custom event because: (a) cross browser custom events are lengthy (b) users can still attach `el.addEventListener('load')` if they for some reason setup `load` or `unload` as a custom event on the element.
Shouldn't be too hard to implement into `yo-yoify` either :) Thanks!
> Add onload/onunload lifecycle properties. Fixes GH-30

- README.md
Thanks for bel!  I have had a great time using it for <https://commonform.org>.
This small doc patch adds a short "security" question with a few notes on XSS mitigation.  I dug into the code and rummaged around GitHub issues to see what, if anything, bel does in terms of escaping and containment.  I imagine this short note may save others the trouble.
Best,
K
> Add "security" README section with XSS notes

- README.md
The message: I borrowed from https://github.com/shama/bel/issues/39#issuecomment-232776543 😄
> Add "yo-yoify" section on README

- index.js
- test/elements.js
Hi! 🐈 
I got Error when I try it through choo 🚋  this below:
```
Uncaught NamespaceError: Uncaught NamespaceError: Failed to execute 'setAttributeNS' on 'Element': '' is an invalid namespace for attributes.
```
minimal case is:
```js
bel`<use xlink:href="#test"></use>`
```
http://requirebin.com/?gist=46114442a147e543dc2ba48ead547fc6
To use `xlink`, we need to `setAttributeNS('http://www.w3.org/1999/xlink', ...`
Thanks:smile:
> support xlink attribute

- index.js
As of now bel simply ignores children that are functions. This change makes bel behave the same as setting a function as `innerHTML` does:
```javascript
function noop() {}
bel`<div>${ noop }</div>` // => <div></div>
var div = document.createElement('div')
div.innerHTML = noop // => <div>function noop() {}</div>
```
My use case is pretty marginal but it makes sense that bel would behave just like `innerHTML` and treat Functions the same way it treats Number, Boolean, Date and RegExp.
> Call toString on functions as children

- index.js
- test/elements.js
Strips empty text nodes, so the resulting DOM is a whole bunch cleaner. Thanks!
> strip empty text nodes

- browser.js
When minifying, property names are often collapsed. This can be problematic when using property names to test set membership. Using an array of strings does not suffer the same problems, and despite lookups being linear rather than constant - this at least keeps working in production. Thanks!
> fix boolean properties for minification

- raw.js
- test/server.js
Related to #84, fixes a small bug on #86, the var `wrapper` was still a primitive and settings properties on a primitive is a no-op, I'm using an instance of the class String instead
> fix(raw): server returns an instance of String instead of a primitive

- bel.d.ts
Rest parameter of `keys` did not have its type, so this PR adds it as `any[]`
> Add explicit any type for 'keys' in bel.d.ts

- package.json
Or anyone has a valid reason for this missing a caret maybe? 
And so, the PR includes:
- Adding ^ (caret) as I see no reason for semver not picking up a patch (for instance)
> Added ^ (caret) for pelo dependency

- test/events.js
- test/index.js
Reference: #99  
Related: #87 
Related:  #https://github.com/choojs/nanomorph/issues/89
Created tests for the events listed in https://github.com/choojs/nanomorph/blob/master/lib/events.js#L32
**NOTE: Failing tests have been commented. You will need to uncomment to run the failing tests.**
The following events fail:
- onfocusin
- onfocusout
- ontouchcancel
- ontouchend
- ontouchmove
- ontouchstart
- onunload
> Added Event tests

- appendChild.js
- test/elements.js
Small fix to ensure whitespace is preserved in textarea. At present, whitespace is being partially stripped.
@yoshuawuyts this fix might need some extra work. I made the smallest change to make the broken test pass, but didn't do more as I'm not familiar with the code. The fix seems slightly wrong, as I had to add "textarea" to the CODE_TAGS array, not TEXT_AREA array.
> Bug fix: ensure whitespace is preserved in textarea

- package.json
This add a build step with umd support. Added to [choojs/choo#617](https://github.com/choojs/choo/pull/617) this would allow devs to use choo completly as a standalone library.
> Add umd build step

- lib/server.js
- tests/server/index.js
These work in newer pelo versions so I'll probably just copy it
> Bunch of fixes for attributes with SSR

- lib/babel.js
- tests/babel/fixtures/svg.expected.js
- tests/babel/fixtures/svg.js
fixes #122 
The babel transform script does not consider `xlink:href` attribute
> adding xlink setAttributeNS to babel transform

- lib/server.js
Hello! 👋 
I'd very much like to help encourage interoperability between the `bel`/`nanohtml` and `hyperscript` ecosystems. In the browser, there are no issues, but in a node environment, some implementation details between `pelo`/`nanohtml/lib/server.js` and [`create-element`](https://github.com/1N50MN14/html-element) make things a little trickier.
When trying to render a hyperscript element inside of a nanohtml statement, I get the following error:
```
$ node example.js
/Users/ng/dev/modules/hyperaxe/node_modules/nanohtml/lib/server.js:61
return Object.keys(value).reduce(function (str, key, i) {
^
RangeError: Maximum call stack size exceeded
at Array.reduce (<anonymous>)
at handleValue (/Users/ng/dev/modules/hyperaxe/node_modules/nanohtml/lib/server.js:61:31)
at …
```
> add server-side hyperscript support

- lib/babel.js
- lib/browser.js
- lib/browserify-transform.js
- lib/direct-props.js
- tests/browser/elements.js
```html
<input type="checkbox" indeterminate="indeterminate">
```
does not work currently, because `indeterminate` needs to be set directly instead of with `el.setAttribute()`.
This should make things work as expected.
> Set indeterminate prop directly, fixes #128

- lib/bool-props.js
- lib/server.js
- package.json
- tests/server/index.js
Add missing boolean properties and fix SSR boolean prop test.
The test for boolean properties only checks that the property name _includes_ a boolean property key, not that the actual property is a match, start to end. This means that attributes such as `aria-selected=${true}` and `data-selected=${true}` would be matched and either removed or have their value replaced with `selected`.
> Fix bool props

- lib/bool-props.js
It seems I was a tad too eager with #132. It turns out that `intermediate` is actually already listed under [lib/direct-props.js](../tree/master/lib/direct-props.js) and `willvalidate` isn't an attribute at all. My bad! 😳
> Remove excess props

- lib/server.js
This is necessary for nanohtml to work on the server via typescript.
The types declarations declares a default export:
```typescript
declare module "nanohtml" {
export default function (strings: TemplateStringsArray, ...keys: any[]): HTMLElement;
// ...
}
```
So its necessary for the code to match. The code in browser.js already does this.
Fixes #130
> Added default export in server code.

- lib/browserify-transform.js
This is a solution for #139. Once I had it reproduced properly, it was relatively clear what was going 😄
> Pass filename to ast-transform for sourcemaps

- lib/browser.js
- lib/set-attribute.js
- tests/browser/elements.js
Previously,
- `<input ${{ disabled: true }}>` added a `disabled="true"` attribute.
- `<input ${{ disabled: false }}>` added a `disabled="false"` attribute.
- `<input ${{ indeterminate: true }}>` added an `indeterminate="true"` attribute.
Now:
- `<input ${{ disabled: true }}>` adds a `disabled="disabled"` attribute.
- `<input ${{ disabled: false }}>` does not add a `disabled` attribute.
- `<input ${{ indeterminate: true }}>` sets `.indeterminate = true` instead of adding an attribute.
> Fix issues with object-spreading boolean and direct props

- lib/babel.js
- lib/browserify-transform.js
We use this as a shorthand in our HUI component, https://github.com/hyperdivision/hui
> add hui/html

- lib/babel.js
- lib/browserify-transform.js
- lib/supported-views.js
Tried moving supported views array to file as suggested in https://github.com/choojs/nanohtml/pull/146#issuecomment-486587379
One thing worth noting: in `lib/browserify-transform.js`, `choo` is included in the list, whereas in `babel.js` it is not. My feeling is that it's not needed (`choo/html` is included in both), but I'd like confirmation of this from a maintainer before moving forward.
cc @goto-bus-stop
> refactor: move supported views array to file

- lib/append-child.js
- tests/browser/elements.js
Hello choo crew :)
I've been having the following issue:
```html
<p>
this
<strong>text</strong>
<p>
```
should render like this:
```html
<p>this <strong>text</strong></p>
```
instead it renders like this:
```html
<p>this<strong>text</strong></p>
```
You can see this in action here: https://vigorous-austin-ab4675.netlify.com/
The first line ("expected") is what gets rendered when I write the HTML manually.
The second line ("actual") is rendered using nanohtml in [this file](https://vigorous-austin-ab4675.netlify.com/index.js).
I've written a failing test case, you can check out 4c56662 to verify that this happens.
The fix is to replace a trailing newline by a space rather than removing it completely.
I hope that this is always the right behavior, I can't think of any other edge case (ie. …
> Trailing newline whitespace should result in a space in text nodes

- lib/browserify-transform.js
- tests/transform/index.js
> Support Typescript synthetic default imports

- lib/append-child.js
- tests/browser/elements.js
#142 was a great start but it didn't quite fix the whitespace issue for me around text nodes. See the test in this PR for an example of a problem I'm running into.
> Preserve trailing newline whitespace before text nodes

- package.json
I noticed that #154 dropped the node tests from the `test` script. This just adds that back in there so all tests are run with `npm test`.
> Add back node test in test script

- lib/browser.js
- tests/browser/multiple.js
This allows for arrays as direct children of document fragments, just like it works with a root node.
```javascript
var train = ['🚂', '🚃', '🚃', '🚃']
html`
<body>
<h1>Hello planet!</h1>
${train.map((char) => html`<span>${char}</span>`)}
</body>
`
```
```javascript
var train = ['🚂', '🚃', '🚃', '🚃']
html`
<h1>Hello planet!</h1>
${train.map((char) => html`<span>${char}</span>`)}
`
```
> Allow arrays in fragments

- lib/server.js
- tests/server/index.js
For convenience nanohtml automatically adds quotes around unquoted attributes, allowing one to write:
```javascript
html`<span class=${'foo'}>Hello there</span>` // <span class="foo">Hello there</span>
```
However, the check for unquoted attributes would also quote query parameters as the syntax looks similar to attributes:
```javascript
html`<a href="/foo?bar=${'baz'}">click me</a>` // <a href="/foo?bar="baz"">click me</a>
```
This change checks wether the part that appears to be an attribute actually is a query. I have tested the regex against these strings and I think that it covers all following scenarios:
```bash 
&foo=
href="foo?bar=
```
```bash
" class=
class=
<div class=
```
> Check for (probable) query before auto-quote

- types/index.d.ts
I'm not the most familiar with how to generate `index.d.ts` files so I just added this by hand while guessing at the types based on a read through the code. It seems to work for my repo, but I don't know if there's a better way to do it (for instance, to separate out the server and browser use cases).
> Add nanohtml/raw to index.d.ts

- README.md
Because users don't have local `./dom`.
> Fix readme to use nanohtml/dom

- README.md
There is a typo in the URL to `jsdom`, raising a PR to correct it
> Typo in URL to jsdom

- lib/server.js
- tests/server/index.js
This change will handle each item of an interpolated array as a potentially unescaped value. The previous implementation (naively) assumed that all items of an array are the result of `html`. In my experience there are several situations where that may not be the case, especially when working with external sources of data, e.g. APIs or a CMS.
An alternative would be to rely on the user running each string in an array through `html` but it seems a bit excessive.
I can't see this breaking anything or having any noticeable negative effect on performance as already formatted results of `html` are identified and returned quickly. So I guess it would count as a minor release.
> Handle all items of array value
